const actionTypes = {
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  UPDATE_CLASS: 'UPDATE_CLASS',
  UPDATE_RACE: 'UPDATE_RACE',
  PICK_ROLL: 'PICK_ROLL',
  SET_SCORE: 'SET_SCORE',
  UPDATE_HOLDER: 'UPDATE_HOLDER',
  SET_ABILITY: 'SET_ABILITY',
  UPDATE_ATTR: 'UPDATE_ATTR',
  MAKE_CHARACTER: 'MAKE_CHARACTER',
  MOD_PAGE: 'MOD_PAGE',
  REROLL: 'REROLL',
};

export default actionTypes;
